---
- name: include hiera extra classes snippet
  blockinfile:
    dest: /etc/puppet/hieradata/{{ puppet_role }}/common.yaml
    insertafter: '---'
    block: |
      # {{ puppet_role }} extra classes
      {{ hiera_classes_extra }}
      # End of {{ puppet_role }} extra classes

- name: include hiera extra params snippet
  blockinfile:
    dest: /etc/puppet/hieradata/{{ puppet_role }}/common.yaml
    marker: "# {{ puppet_role }} extra params #"
    insertafter: '# End of {{ puppet_role }} extra classes'
    block: |
      {{ hiera_params_extra }}
