---
- name: create /etc/openstack
  file: path=/etc/openstack state=directory

- name: generate clouds.yaml
  blockinfile:
    dest: /etc/openstack/clouds.yaml
    create: yes
    block: |
      clouds:
        openstack:
          auth:
            auth_url: http://{{ ansible_host }}:35357/
            project_name: openstack
            username: admin
            password: a_big_secret
          region_name: RegionOne

- name: validate keystone is working
  os_auth:
    cloud: openstack
