- name: install puppetlabs-release
  yum:
    name: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
    state: present

- name: puppet and dependencies
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - libxml2-devel
    - libxslt-devel
    - puppet
    - python-pip
    - ruby-devel
    - rubygems
    - wget

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: install r10k
  gem:
    name: r10k
    user_install: no

- name: download Puppetfile
  get_url:
    url: https://raw.githubusercontent.com/openstack/puppet-openstack-integration/master/Puppetfile
    dest: /tmp/Puppetfile

- name: deploy puppet modules
  shell: /usr/local/bin/r10k puppetfile install -v
  environment:
    PUPPETFILE_DIR: /etc/puppet/modules
    PUPPETFILE: /tmp/Puppetfile

