---
- name: include mysql hiera snippet
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    marker: "# mysql class #"
    insertafter: 'classes:'
    block: |
      # deploy mysql server
        - mysql::server

- name: include mysql data in hiera common
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    marker: "# mysql data #"
    insertbefore: 'classes:'
    block: |
      mysql::server::override_options:
        mysqld:
          max_connections: {{ mysql_max_connections }}
          restart: true
