---
- name: include mysql hiera snippet
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    marker: "# mysql class #"
    insertafter: 'classes:'
    block: |
      # deploy mysql server
        - openstack_integration::mysql
