---

- name: include mysql puppet classes in hiera common
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    marker: "# mysql class #"
    insertafter: 'classes:'
    block: |
      # deploy mysql server
        - openstack_integration::mysql

- name: validate mysql is working
  mysql_db:
    name: dbtest
    state: present
  tags:
    - validation
