---
# this playbook is common to all nodes.

###################
# puppet manifest #
###################
- name: create /etc/puppet/manifests
  file:
    path: /etc/puppet/manifests
    state: directory

- name: create site.pp
  blockinfile:
    dest: /etc/puppet/manifests/site.pp
    create: yes
    block: |
      Exec {
        path => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
      }
      hiera_include('classes')

###############
# puppet data #
###############
- name: configure hiera.yaml
  blockinfile:
    dest: /etc/puppet/hiera.yaml
    create: yes
    block: |
      ---
      :backends:
        - yaml
      :hierarchy:
        - "%{::role}/common"
        - common
      :yaml:
        :datadir: /etc/puppet/hieradata

- name: cleanup /etc/puppet/hieradata
  file:
    path: /etc/puppet/hieradata
    state: absent

- name: create /etc/puppet/hieradata
  file:
    path: /etc/puppet/hieradata
    state: directory

- name: create hieradata/common
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    create: yes
    block: |
      ---
      classes:
        - openstack_integration
        - openstack_integration::repos

- name: create /etc/puppet/hieradata/{{ puppet_role }}
  file:
    path: /etc/puppet/hieradata/{{ puppet_role }}
    state: directory

- name: create hieradata/{{ puppet_role }}/common
  blockinfile:
    dest: /etc/puppet/hieradata/{{ puppet_role }}/common.yaml
    create: yes
    marker: "# specific to {{ puppet_role }} #"
    block: |
      ---

- name: add hiera validation data
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    marker: "# hiera validation #"
    insertbefore: "classes:"
    block: |
      hiera_validate: true

- name: validate hiera is working
  shell: "hiera hiera_validate -c /etc/puppet/hiera.yaml | grep -q true"
  register: hiera_result
  failed_when: "hiera_result.rc != 0"

- name: create /etc/facter/facts.d
  file:
    path: /etc/facter/facts.d
    state: directory

- name: create facter environment
  blockinfile:
    dest: /etc/facter/facts.d/environment.txt
    create: yes
    block: |
      role={{ puppet_role }}
