---
# this playbook is common to all nodes.

- name: install puppetlabs-release
  yum: name=https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm state=present

- name: puppet and dependencies
  yum: name={{ item }} state=latest
  with_items:
    - puppet
    - libxml2-devel
    - libxslt-devel
    - ruby-devel
    - rubygems
    - wget

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: configure hiera.yaml
  blockinfile:
    dest: /etc/puppet/hiera.yaml
    create: yes
    block: |
      ---
      :backends:
        - yaml
      :hierarchy:
        - "%{::role}/common"
        - common
      :yaml:
        :datadir: /etc/puppet/hieradata

- name: create /etc/puppet/manifests
  file: path=/etc/puppet/manifests state=directory

- name: create site.pp
  blockinfile:
    dest: /etc/puppet/manifests/site.pp
    create: yes
    block: |
      Exec {
        path => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'
      }
      hiera_include('classes')

- name: create /etc/puppet/hieradata
  file: path=/etc/puppet/hieradata state=directory

- name: create hieradata/common
  blockinfile:
    dest: /etc/puppet/hieradata/common.yaml
    create: yes
    block: |
      ---
      classes:
        - openstack_integration

- name: install r10k
  gem: name=r10k user_install=no

- name: download Puppetfile
  get_url: url=https://raw.githubusercontent.com/openstack/puppet-openstack-integration/master/Puppetfile dest=/tmp/Puppetfile

- name: deploy puppet modules
  shell: /usr/local/bin/r10k puppetfile install -v
  environment:
    PUPPETFILE_DIR: /etc/puppet/modules
    PUPPETFILE: /tmp/Puppetfile

