---
- name: include hiera extra classes snippet
  blockinfile:
    dest: /etc/puppet/hieradata/{{ puppet_role }}/common.yaml
    insertafter: "---"
    block: |
      {{ hiera_classes_extra }}
      {{ hiera_params_extra }}
